# apiVersion: kubeadm.k8s.io/v1alpha3
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
# api:
#   advertiseAddress: 192.168.50.10
# apiServerCertSANs:
# - 192.168.50.13
apiServer:
  certSANs:
  - "192.168.50.13"
  extraArgs: 
    apiserver-count: "2"
  
controlPlaneEndpoint: "192.168.50.13:6443"
etcd:
  external:
    endpoints:
    - https://192.168.50.12:2379
    - https://192.168.50.11:2379
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 192.168.0.0/16
# apiServerExtraArgs:
#   apiserver-count: "2"